version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: pr-reviewer-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: prdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: pr-reviewer-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:pass@db:5432/prdb?sslmode=disable
    command: >
      sh -c "
      sleep 5 &&
      ./main
      "

volumes:
  pgdata: